apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
      - "--dockerfile=/workspace/Dockerfile"
      - "--context=dir:///workspace"
      - "--destination=rharp/devops-toolkit:1.0.0"
      - "--tarPath=/workspace/kaniko-demo.tar"
      - "--no-push"
    volumeMounts:
      - name: kaniko-volume
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-volume
      hostPath:
        path: /Users/rickharp/projects/github/kaniko-demo
        type: Directory

